### ISSUE TITLE
Minor point of confusion : Naming of cmd files

### ISSUE THREAD

**Issue by SteveBurkettNZ** [Microsoft/AADConnectConfigDocumenter#16]
The naming of the AzureADConnectSyncDocumenterCmd.exe file can cause minor confusion when following the instructions, as the .exe extension is hidden by default in Windows Explorer.

It's therefore easy to incorrectly assume the AzureADConnectSyncDocumenterCmd file is the one you want to be editing the paths in, and get greeted by a bunch of gibberish when opened in Notepad.

Possibly rename the .exe or .cmd file to something more distinguished?

**Comment by NileshGhodekar** [comment]
Hi Steve,

Thank you for the feedback! Yes, I've seen this reported rarely.  And even more frequently people downloading the source code instead of the release and complaining not able to run the report. We'll not be able to change the file name of the .exe as that has the potential to lead to even more serious backward compatibility issues, but can look at renaming the sample .cmd script file. In fact, I was planning to rename it to AzureADConnectSyncDocumenter-Contoso.cmd so that you can have your own with your customer name without the fear of overwrite during the new build, but always forgot to check-in the change. So I'll keep this open for now and will close once I make the changes for both the issues.

**Comment by NileshGhodekar** [comment]
Closing this issue with the release of latest version v1.18.0928.0.
